export const SYSTEM_SETTING_ICONS = [
  { label: 'Videogames - Joystick / Controle', value: 'fa-gamepad' },
  { label: 'Loja', value: 'fa-store' },
  { label: 'Carro', value: 'fa-car' },
  { label: 'Ferramentas', value: 'fa-screwdriver-wrench' },
  { label: 'Empresa', value: 'fa-building' },
  { label: 'Cinema', value: 'fa-film' },
  { label: 'Casa', value: 'fa-house' },
  { label: 'Caminhão', value: 'fa-truck' },
  { label: 'Moto', value: 'fa-motorcycle' },
  { label: 'Bicicleta', value: 'fa-bicycle' },
  { label: 'Ônibus', value: 'fa-bus' },
  { label: 'Avião', value: 'fa-plane' },
  { label: 'Barco', value: 'fa-ship' },
  { label: 'Computador', value: 'fa-desktop' },
  { label: 'Notebook', value: 'fa-laptop' },
  { label: 'Celular', value: 'fa-mobile-screen-button' },
  { label: 'Câmera', value: 'fa-camera' },
  { label: 'Música', value: 'fa-music' },
  { label: 'Fones de ouvido', value: 'fa-headphones' },
  { label: 'Televisão', value: 'fa-tv' },
  { label: 'Livro', value: 'fa-book' },
  { label: 'Formatura', value: 'fa-graduation-cap' },
  { label: 'Restaurante', value: 'fa-utensils' },
  { label: 'Café', value: 'fa-mug-hot' },
  { label: 'Carrinho de compras', value: 'fa-cart-shopping' },
  { label: 'Sacola de compras', value: 'fa-bag-shopping' },
  { label: 'Presente', value: 'fa-gift' },
  { label: 'Estrela', value: 'fa-star' },
  { label: 'Coração', value: 'fa-heart' },
  { label: 'Bola de futebol', value: 'fa-futbol' },
  { label: 'Academia', value: 'fa-dumbbell' },
  { label: 'Árvore', value: 'fa-tree' },
  { label: 'Folha', value: 'fa-leaf' },
  { label: 'Maleta', value: 'fa-briefcase' },
  { label: 'Engrenagem', value: 'fa-gear' },
  { label: 'Caixa', value: 'fa-box' },
  { label: 'Videogames - Headset gamer', value: 'fa-headset' },
  { label: 'Videogames - Realidade virtual', value: 'fa-vr-cardboard' },
  { label: 'Videogames - Fantasma', value: 'fa-ghost' },
  { label: 'Videogames - Robô', value: 'fa-robot' },
  { label: 'Videogames - Dragão RPG', value: 'fa-dragon' },
  { label: 'Videogames - Dado RPG', value: 'fa-dice-d20' },
  { label: 'Videogames - Dados', value: 'fa-dice' },
  { label: 'Videogames - Troféu', value: 'fa-trophy' },
  { label: 'Videogames - Mira', value: 'fa-crosshairs' },
  { label: 'Videogames - Escudo', value: 'fa-shield-halved' },
  { label: 'Videogames - Energia', value: 'fa-bolt' },
  { label: 'Videogames - Quebra-cabeça', value: 'fa-puzzle-piece' },
  { label: 'Videogames - Xadrez', value: 'fa-chess-knight' },
  { label: 'Videogames - Foguete', value: 'fa-rocket' },
  { label: 'Videogames - Caveira', value: 'fa-skull' },
  { label: 'Videogames - Moedas', value: 'fa-coins' },
  { label: 'Videogames - Console PlayStation', value: 'fa-playstation' },
  { label: 'Videogames - Console Xbox', value: 'fa-xbox' },
];
